ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= Antora

IMPORTANT: The commands below are based on a bash shell, so keep attention to run those on it!

== First deploy

To start with the scaffold, simply type those following commands:

```
npm run init
```

After this, you will access the site locally (via your own LiveServer) in the directory:
```
\build\antora\public\index.html
```

== Future builds

Then afterwards to build all modules of the local web version (Antora) you just have to run:
```
npm run build
```

== Clean your repository for local test purpose only

You can wipe all following content by running the command below:

- supplemental_ui 
- build 

```
npm run clean
```

For a full wiping concerning those documents also run the command below:

- .gitignore 
- .gitlab-ci.yml
- package-lock.json
- node_modules 

```
npm run wipe
```

== Adoc and confluence

Instruction to build one of the modules of the transferable version in the Confluences pages:

```
npm run --silent confluence --location=docs/modules/user-nborgognon
```

After building up in this way, the pages as well as the tree structure (and assets) to be transferred to Confluence are available in the directory: 

```
\build\confluence\target\asciidoc-confluence-publisher\assets\[no de build]
```
